### PR TITLE
fix: improve safety

### LINKED ISSUE #8: DropStructMacroDerive will drop null vectors
When `Vec::from_raw_parts` is called, the pointer _must_ be non-null and must refer to allocated memory.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #8, #7

cc @Stebalien

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@vmx any idea what the issue with CI here is?

**Review by Stebalien — APPROVED** [review]
I'd also take a look at https://github.com/filecoin-project/filecoin-ffi/pull/229. We can probably avoid a lot of these helpers if we create FFI-safe types that implement drop.

**Comment by vmx** [comment]
@dignifiedquire see https://github.com/filecoin-project/rust-fil-ffi-toolkit/pull/12 for a fix.

**Comment by dignifiedquire** [comment]
closing, moving to a world where filecoin-ffi doesn't use this crate anymore

**Pull request closed without merging**
